version: '3.4'

services:
  app:
    image: fireflyiii/core:latest
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
      - reverse_proxy
    volumes:
      - upload:/var/www/html/storage/upload
    env_file: .env
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.fireflyiii.entrypoints=web"
      - "traefik.http.routers.fireflyiii.rule=Host(`${FIREFLYIII_DOMAIN:-fireflyiii.localhost}`)"
      - "traefik.http.routers.fireflyiii.middlewares=local-service@file,force-http@file"
      - "traefik.http.services.fireflyiii.loadbalancer.server.port=8080"
      # HTTPS router
      - "traefik.http.routers.fireflyiii-https.entrypoints=websecure"
      - "traefik.http.routers.fireflyiii-https.rule=Host(`${FIREFLYIII_DOMAIN:-fireflyiii.localhost}`)"
      - "traefik.http.routers.fireflyiii-https.tls=true"
      - "traefik.http.routers.fireflyiii-https.middlewares=local-service@file,force-http@file"
    
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

volumes:
   upload:
   db:

networks:
  reverse_proxy:
    external: true