version: '3.5'

services:
  vaultwarden:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    volumes:
      - data:/data
    env_file:
      - .env
    networks:
      - nginx

networks:
  nginx:
    external: true

volumes:
  data: