services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.25.2
    hostname: ${VAULTWARDEN_DOMAIN:-vaultwarden.localhost}
    restart: unless-stopped
    networks:
      - reverse_proxy
    volumes:
      - data:/data
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.vaultwarden.entrypoints=web"
      - "traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_DOMAIN:-vaultwarden.localhost}`)"
      - "traefik.http.routers.vaultwarden.middlewares=force-https@file"
      # HTTPS router
      - "traefik.http.routers.vaultwarden-https.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-https.rule=Host(`${VAULTWARDEN_DOMAIN:-vaultwarden.localhost}`)"
      - "traefik.http.routers.vaultwarden-https.tls=true"
      - "traefik.http.routers.vaultwarden-https.tls.certresolver=cloudflare"
    env_file: .env

volumes:
  data:

networks:
  reverse_proxy:
    external: true