version: '3.5'

services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - '80:80'
      - '443:443'
    environment:
      DB_MYSQL_HOST: 'database'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'nginx_proxy_manager'
      DB_MYSQL_PASSWORD: 'nginx_proxy_manager'
      DB_MYSQL_NAME: 'nginx_proxy_manager'
    volumes:
      - ./nginx:/data/nginx/custom
      - nginx:/data
      - letsenctypt:/etc/letsencrypt
    networks:
      - default
      - nginx
  database:
    image: 'mariadb:10.6'
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'nginx_proxy_manager'
      MYSQL_USER: 'nginx_proxy_manager'
      MYSQL_PASSWORD: 'nginx_proxy_manager'
    volumes:
      - database:/var/lib/mysql

networks:
  nginx:
    external: true

volumes:
  nginx:
  letsenctypt:
  database:
