version: '3.5'

services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    depends_on:
      - db
    # For security reasons, only inside the host the port 81 is available.
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:81:81'
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'nginx_proxy_manager'
      DB_MYSQL_PASSWORD: 'nginx_proxy_manager'
      DB_MYSQL_NAME: 'nginx_proxy_manager'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx:/data/nginx/custom
    networks:
      - default
      - nginx
  nginx_exporter:
    image: 'nginx/nginx-prometheus-exporter:0.9.0'
    depends_on:
      - nginx_proxy_manager
    expose:
      - '9113'
    networks:
      - monitoring
      - nginx
    command:
      - '-nginx.scrape-uri=http://nginx_proxy_manager:8080/stub_status'
    labels:
      org.label-schema.group: "monitoring"
  db:
    image: 'mariadb:10'
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'nginx_proxy_manager'
      MYSQL_USER: 'nginx_proxy_manager'
      MYSQL_PASSWORD: 'nginx_proxy_manager'
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  nginx:
    external: true
  monitoring:
    external: true
