version: '3.5'

services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'nginx_proxy_manager'
      DB_MYSQL_PASSWORD: 'nginx_proxy_manager'
      DB_MYSQL_NAME: 'nginx_proxy_manager'
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
      - ./nginx:/data/nginx/custom
    networks:
      - default
      - nginx
  db:
    image: 'mariadb:10.6'
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'nginx_proxy_manager'
      MYSQL_USER: 'nginx_proxy_manager'
      MYSQL_PASSWORD: 'nginx_proxy_manager'
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  nginx:
    external: true
