version: '3.5'

services:
  pihole:
    image: 'pihole/pihole:latest'
    container_name: pihole
    restart: unless-stopped
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    networks:
      - default
      - nginx
    env_file: .env
    environment:
      DNSMASQ_LISTENING: all

volumes:
  pihole:
  dnsmasq:

networks:
  nginx:
    external: true