services:
  pihole:
    image: pihole/pihole:2022.04
    hostname: ${PIHOLE_DOMAIN:-pihole.localhost}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - default
      - reverse_proxy
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    env_file: .env
    environment:
      DNSMASQ_LISTENING: all
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_DOMAIN:-pihole.localhost}`)"
      - "traefik.http.routers.pihole.middlewares=local-service@file"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # Watchtower
      - "com.centurylinklabs.watchtower.monitor-only=true"

volumes:
  pihole:
  dnsmasq:

networks:
  reverse_proxy:
    external: true