version: '3.5'

services:
  pihole:
    image: 'pihole/pihole:latest'
    container_name: pihole
    restart: unless-stopped
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '82:80/tcp'
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    env_file: .env

volumes:
  pihole:
  dnsmasq: