services:
  app:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.8.0
    hostname: ${PAPERLESS_DOMAIN:-paperless.localhost}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - scheduler
    networks:
      - default
      - reverse_proxy
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.paperless.entrypoints=web"
      - "traefik.http.routers.paperless.rule=Host(`${PAPERLESS_DOMAIN:-paperless.localhost}`)"
      - "traefik.http.routers.paperless.middlewares=force-https@file"
      # HTTPS router
      - "traefik.http.routers.paperless-https.entrypoints=websecure"
      - "traefik.http.routers.paperless-https.rule=Host(`${PAPERLESS_DOMAIN:-paperless.localhost}`)"
      - "traefik.http.routers.paperless-https.tls=true"
      - "traefik.http.routers.paperless-https.tls.certresolver=cloudflare"
    env_file:
      - .env
    environment:
      PAPERLESS_REDIS: redis://scheduler:6379
  scheduler:
    image: redis
    restart: unless-stopped    

volumes:
  data:
  media:

networks:
  reverse_proxy:
    external: true
