services:
  traefik:
    image: traefik:v2.8.1
    hostname: raspberrypi
    restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - default
      - reverse_proxy
    volumes:
      - ./config/configuration.yaml:/app/configuration.yaml:ro
      - data:/certificates
    command: 
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.endpoint=http://proxy:2375
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=reverse_proxy
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.file.filename=/app/configuration.yaml
      - --certificatesresolvers.letsencrypt.acme.email=bailetti.tommaso@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt-staging.acme.email=bailetti.tommaso@gmail.com
      - --certificatesresolvers.letsencrypt-staging.acme.storage=/certificates/acme-staging.json
      - --certificatesresolvers.letsencrypt-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt-staging.acme.tlschallenge=true

  proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - NETWORKS=1
      - TASKS=1
networks:
  reverse_proxy:
    external: true

volumes:
  data: