version: '3.5'

services:
  traefik:
    image: traefik:v2.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/configuration.yaml:/app/configuration.yaml:ro
      - data:/certificates
    networks:
      - reverse_proxy
    command: 
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.file.filename=/app/configuration.yaml
      - --certificatesresolvers.letsencrypt.acme.email=bailetti.tommaso@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt-staging.acme.email=bailetti.tommaso@gmail.com
      - --certificatesresolvers.letsencrypt-staging.acme.storage=/certificates/acme-staging.json
      - --certificatesresolvers.letsencrypt-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt-staging.acme.tlschallenge=true

networks:
  reverse_proxy:
    external: true

volumes:
  data: