version: '3.5'

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    hostname: ${PROWLARR_DOMAIN:-prowlarr.localhost}
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    volumes:
      - prowlarr:/config
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_DOMAIN:-prowlarr.localhost}`)"
      - "traefik.http.routers.prowlarr.middlewares=local-service@file"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

  transmission:
    image: linuxserver/transmission
    hostname: ${TRANSMISSION_DOMAIN:-transmission.localhost}
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    volumes:
      - transmission:/config
      - ${STORAGE_PATH:-./data}/downloads:/downloads
    logging:
      driver: json-file
      options:
        max-size: 10m
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.routers.transmission.rule=Host(`${TRANSMISSION_DOMAIN:-transmission.localhost}`)"
      - "traefik.http.routers.transmission.middlewares=local-service@file"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

  sonarr:
    image: linuxserver/sonarr
    hostname: ${SONARR_DOMAIN:-sonarr.localhost}
    restart: unless-stopped
    depends_on:
      - prowlarr
      - transmission
    networks:
      - default
      - reverse_proxy
    volumes:
      - sonarr:/config
      - ${STORAGE_PATH:-./data}/media/tv:/tv
      - ${STORAGE_PATH:-./data}/downloads:/downloads
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.routers.sonarr.rule=Host(`${SONARR_DOMAIN:-sonarr.localhost}`)"
      - "traefik.http.routers.sonarr.middlewares=local-service@file"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  radarr:
    image: linuxserver/radarr
    hostname: ${RADARR_DOMAIN:-radarr.localhost}
    restart: unless-stopped
    depends_on:
      - prowlarr
      - transmission
    networks:
      - default
      - reverse_proxy
    volumes:
      - radarr:/config
      - ${STORAGE_PATH:-./data}/media/movies:/movies
      - ${STORAGE_PATH:-./data}/downloads:/downloads
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.routers.radarr.rule=Host(`${RADARR_DOMAIN:-radarr.localhost}`)"
      - "traefik.http.routers.radarr.middlewares=local-service@file"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  bazarr:
    image: linuxserver/bazarr
    hostname: ${BAZARR_DOMAIN:-bazarr.localhost}
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    volumes:
      - bazarr:/config
      - ${STORAGE_PATH:-./data}/media/movies:/mnt/data/media/movies
      - ${STORAGE_PATH:-./data}/media/tv:/mnt/data/media/tv
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.bazarr.entrypoints=web"
      - "traefik.http.routers.bazarr.rule=Host(`${BAZARR_DOMAIN:-bazarr.localhost}`)"
      - "traefik.http.routers.bazarr.middlewares=local-service@file"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"

  jellyfin:
    image: linuxserver/jellyfin
    hostname: ${JELLYFIN_DOMAIN:-jellyfin.localhost}
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    volumes:
      - ${STORAGE_PATH:-./data}/media:/mnt/media
      - jellyfin:/config
      - /opt/vc/lib:/opt/vc/lib
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_DOMAIN:-jellyfin.localhost}`)"
      - "traefik.http.routers.jellyfin.middlewares=local-service@file"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

volumes:
  prowlarr:
  sonarr:
  radarr:
  bazarr:
  jellyfin:
  transmission:

networks:
  reverse_proxy:
    external: true