services:
  prowlarr:
    image: linuxserver/prowlarr:0.4.7-nightly
    hostname: ${PROWLARR_DOMAIN:-prowlarr.localhost}
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    volumes:
      - prowlarr:/config
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_DOMAIN:-prowlarr.localhost}`)"
      - "traefik.http.routers.prowlarr.middlewares=local-service@file"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    env_file: .env

  torrent:
    image: linuxserver/transmission:version-3.00-r5
    hostname: ${TORRENT_DOMAIN:-torrent.localhost}
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    volumes:
      - torrent:/config
      - ${STORAGE_PATH:-./data}/downloads:/downloads
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.torrent.entrypoints=web"
      - "traefik.http.routers.torrent.rule=Host(`${TORRENT_DOMAIN:-torrent.localhost}`)"
      - "traefik.http.routers.torrent.middlewares=local-service@file"
      - "traefik.http.services.torrent.loadbalancer.server.port=9091"
    env_file: .env

  sonarr:
    image: linuxserver/sonarr:3.0.10
    hostname: ${SONARR_DOMAIN:-sonarr.localhost}
    restart: unless-stopped
    depends_on:
      - prowlarr
      - torrent
    networks:
      - default
      - reverse_proxy
    volumes:
      - sonarr:/config
      - ${STORAGE_PATH:-./data}/media/tv:/tv
      - ${STORAGE_PATH:-./data}/downloads:/downloads
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.routers.sonarr.rule=Host(`${SONARR_DOMAIN:-sonarr.localhost}`)"
      - "traefik.http.routers.sonarr.middlewares=local-service@file"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    env_file: .env

  radarr:
    image: linuxserver/radarr:4.2.4
    hostname: ${RADARR_DOMAIN:-radarr.localhost}
    restart: unless-stopped
    depends_on:
      - prowlarr
      - torrent
    networks:
      - default
      - reverse_proxy
    volumes:
      - radarr:/config
      - ${STORAGE_PATH:-./data}/media/movies:/movies
      - ${STORAGE_PATH:-./data}/downloads:/downloads
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.routers.radarr.rule=Host(`${RADARR_DOMAIN:-radarr.localhost}`)"
      - "traefik.http.routers.radarr.middlewares=local-service@file"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    env_file: .env

  bazarr:
    image: linuxserver/bazarr:1.1.1
    hostname: ${BAZARR_DOMAIN:-bazarr.localhost}
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
    networks:
      - default
      - reverse_proxy
    volumes:
      - bazarr:/config
      - ${STORAGE_PATH:-./data}/media/movies:/movies
      - ${STORAGE_PATH:-./data}/media/tv:/tv
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.bazarr.entrypoints=web"
      - "traefik.http.routers.bazarr.rule=Host(`${BAZARR_DOMAIN:-bazarr.localhost}`)"
      - "traefik.http.routers.bazarr.middlewares=local-service@file"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    env_file: .env

  jellyfin:
    image: linuxserver/jellyfin:10.8.5
    hostname: ${JELLYFIN_DOMAIN:-jellyfin.localhost}
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
    volumes:
      - ${STORAGE_PATH:-./data}/media:/mnt/media
      - jellyfin:/config
      - /opt/vc/lib:/opt/vc/lib
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_DOMAIN:-jellyfin.localhost}`)"
      - "traefik.http.routers.jellyfin.middlewares=local-service@file"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    env_file: .env

volumes:
  prowlarr:
  sonarr:
  radarr:
  bazarr:
  jellyfin:
  torrent:

networks:
  reverse_proxy:
    external: true
