version: '3.5'

services:
  jackett:
    image: 'linuxserver/jackett'
    container_name: jackett
    restart: unless-stopped
    volumes:
      - jackett:/config/Jackett
    networks:
      - default
      - nginx
    env_file:
      - .env
  transmission:
    image: 'linuxserver/transmission'
    container_name: transmission
    restart: unless-stopped
    volumes: 
      - ./data:/mnt/data
      - transmission:/config
    networks:
      - default
      - nginx
    logging:
      driver: json-file
      options:
        max-size: 10m
    env_file:
      - .env
  sonarr:
    image: 'linuxserver/sonarr'
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - jackett
      - transmission
    volumes:
      - sonarr:/config
      - ./data:/mnt/data
    networks:
      - default
      - nginx
    env_file:
      - .env
  radarr:
    image: 'linuxserver/radarr'
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - jackett
      - transmission
    volumes:
      - radarr:/config
      - ./data:/mnt/data
    networks:
      - default
      - nginx
    env_file:
      - .env
  bazarr:
    image: 'linuxserver/bazarr'
    container_name: bazarr
    restart: unless-stopped
    volumes:
      - bazarr:/config
      - ./data/media/movies:/mnt/data/media/movies
      - ./data/media/tv:/mnt/data/media/tv
    networks:
      - default
      - nginx
    env_file:
      - .env
  jellyfin:
    image: 'linuxserver/jellyfin'
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - '8096:8096'
      - '8920:8920'
      - '7359:7359/udp'
      - '1900:1900/udp'
    volumes:
      - ./data/media:/mnt/media
      - jellyfin:/config
      - /opt/vc/lib:/opt/vc/lib
    networks:
      - default
      - nginx
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    env_file:
      - .env

volumes:
  jackett:
  transmission:
  sonarr:
  radarr:
  bazarr:
  jellyfin:

networks:
  nginx:
    external: true