version: '3.5'

services:
  app:
    image: 'nextcloud'
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - data:/var/www/html
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    networks:
      - default
      - nginx
  db:
    image: 'mariadb:10'
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    command:
      - '--transaction-isolation=READ-COMMITTED'
      - '--binlog-format=ROW'

networks:
  nginx:
    external: true

volumes:
  data:
  db: