services:
  app:
    image: 'nextcloud'
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - data:/var/www/html
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
    networks:
      - default
      - nginx
  db:
    image: 'postgres'
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud

networks:
  nginx:
    external: true

volumes:
  data:
  db: