version: '3.5'

services:
  prometheus:
    image: 'prom/prometheus:v2.30.3'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
      - reverse_proxy
    labels:
      - "org.label-schema.group=monitoring"
      ## Traefik
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`${PROMETHEUS_DOMAIN:-prometheus.localhost}`)"
      - "traefik.http.routers.portainer.middlewares=local-service@file,force-http@file"
      - "traefik.http.services.portainer.loadbalancer.server.port=9090"
      # HTTPS router
      - "traefik.http.routers.portainer-https.entrypoints=websecure"
      - "traefik.http.routers.portainer-https.rule=Host(`${PROMETHEUS_DOMAIN:-prometheus.localhost}`)"
      - "traefik.http.routers.portainer-https.tls=true"
      - "traefik.http.routers.portainer-https.middlewares=local-service@file,force-http@file"
      
  alertmanager:
    image: 'prom/alertmanager:v0.23.0'
    restart: unless-stopped
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring
      - reverse_proxy
    labels:
      - "org.label-schema.group=monitoring"
      ## Traefik
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`${ALERTMANAGER_DOMAIN:-alertmanager.localhost}`)"
      - "traefik.http.routers.portainer.middlewares=local-service@file,force-http@file"
      - "traefik.http.services.portainer.loadbalancer.server.port=9093"
      # HTTPS router
      - "traefik.http.routers.portainer-https.entrypoints=websecure"
      - "traefik.http.routers.portainer-https.rule=Host(`${ALERTMANAGER_DOMAIN:-alertmanager.localhost}`)"
      - "traefik.http.routers.portainer-https.tls=true"
      - "traefik.http.routers.portainer-https.middlewares=local-service@file,force-http@file"

  nodeexporter:
    image: 'prom/node-exporter:v1.2.2'
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    labels:
      - "org.label-schema.group=monitoring"

  cadvisor:
    image: 'zcube/cadvisor:v0.37.5'
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    command:
      - '--housekeeping_interval=10s'
      - '--max_housekeeping_interval=1m'
      - '--allow_dynamic_housekeeping=true'
      - '--storage_duration=1s'
      - '--docker_only=true'
    networks:
      - monitoring
    labels:
      - "org.label-schema.group=monitoring"

  grafana:
    image: 'grafana/grafana:8.2.1'
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring
      - reverse_proxy
    labels:
      - "org.label-schema.group=monitoring"
      ## Traefik
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`${GRAFANA_DOMAIN:-grafana.localhost}`)"
      - "traefik.http.routers.portainer.middlewares=local-service@file,force-http@file"
      - "traefik.http.services.portainer.loadbalancer.server.port=3000"
      # HTTPS router
      - "traefik.http.routers.portainer-https.entrypoints=websecure"
      - "traefik.http.routers.portainer-https.rule=Host(`${GRAFANA_DOMAIN:-grafana.localhost}`)"
      - "traefik.http.routers.portainer-https.tls=true"
      - "traefik.http.routers.portainer-https.middlewares=local-service@file,force-http@file"

  pushgateway:
    image: prom/pushgateway:v1.4.2
    restart: unless-stopped
    networks:
      - monitoring
    labels:
      - "org.label-schema.group=monitoring"

volumes:
    prometheus:
    grafana:

networks:
  monitoring:
    external: true
  reverse_proxy:
    external: true