services:
  app:
    image: netdata/netdata:v1.35.1
    hostname: ${NETDATA_DOMAIN:-netdata.localhost}
    restart: unless-stopped
    depends_on:
      - proxy
    networks:
      - default
      - reverse_proxy
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    configs:
      - source: conf
        target: /etc/netdata/netdata.conf
      - source: alarms
        target: /etc/netdata/health_alarm_notify.conf
    volumes:
      - config:/etc/netdata
      - lib:/var/lib/netdata
      - cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.netdata.entrypoints=web"
      - "traefik.http.routers.netdata.rule=Host(`${NETDATA_DOMAIN:-netdata.localhost}`)"
      - "traefik.http.routers.netdata.middlewares=local-service@file"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
    environment:
      - DOCKER_HOST=proxy:2375
  proxy:
    image: tecnativa/docker-socket-proxy:0.1.1
    restart: unless-stopped
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1

volumes:
  config:
  lib:
  cache:

configs:
  alarms:
    file: ./docker-compose.yml
  conf:
    file: ./health_alarm_notify.conf

networks:
  reverse_proxy:
    external: true