services:
  netdata:
    image: netdata/netdata
    hostname: ${NETDATA_DOMAIN:-netdata.localhost}
    restart: unless-stopped
    depends_on:
      - proxy
    networks:
      - default
      - reverse_proxy
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - ./netdata.conf:/etc/netdata/netdata.conf:ro
      - ./health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf:ro
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - DOCKER_HOST=proxy:2375
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.netdata.entrypoints=web"
      - "traefik.http.routers.netdata.rule=Host(`${NETDATA_DOMAIN:-netdata.localhost}`)"
      - "traefik.http.routers.netdata.middlewares=local-service@file"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
  proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  reverse_proxy:
    external: true