services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server:2022.10.0-java17
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ${STORAGE_PATH:-./data}:/data
    env_file:
      - .env
    environment:
      EULA: "TRUE"
