services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    restart: unless-stopped
    configs:
      - source: conf
        target: /config/ddclient.conf
    env_file:
      - .env

configs:
  conf:
    file: ./ddclient.conf
