services:
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient:3.10.0
    restart: unless-stopped
    configs:
      - source: conf
        target: /config/ddclient.conf
    env_file: .env

configs:
  conf:
    file: ./ddclient.conf
