services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    restart: unless-stopped
    ports:
      - "${SERVERPORT:-51820}:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    env_file: .env
    environment:
      LOG_CONFS: false
